import io
import re
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from src.core.models import SDSDocument
from src.core.logger import logger


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and render total page count on footer."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#718096"))
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(A4[0] - 36, 20, page_text)
        self.drawString(36, 20, "ChemShield AI — GHS Safety Data Sheet (OSHA HazCom 2012)")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(36, 32, A4[0] - 36, 32)
        self.restoreState()


def generate_sds_pdf(sds: SDSDocument, warning_banner: str | None = None) -> bytes:
    """
    Generate a multi-page PDF document for a 16-section GHS Safety Data Sheet.
    Returns raw PDF bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=45
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'SDSTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#1A365D'),
        spaceAfter=4
    )

    subtitle_style = ParagraphStyle(
        'SDSSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#4A5568'),
        spaceAfter=12
    )

    draft_banner_style = ParagraphStyle(
        'DraftBanner',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor('#856404')
    )

    section_header_style = ParagraphStyle(
        'SDSSectionHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        textColor=colors.white,
        spaceBefore=0,
        spaceAfter=0
    )

    body_style = ParagraphStyle(
        'SDSBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor('#2D3748'),
        spaceAfter=6
    )

    story = []

    # 1. Top DRAFT Notice Banner
    draft_text = (
        "<b>DRAFT — AI-GENERATED DOCUMENT:</b> This Safety Data Sheet was generated by an AI system "
        "and has NOT been certified, verified, or approved by a Certified Safety Professional (CSP). "
        "It MUST NOT be used for regulatory compliance or workplace distribution without full expert review."
    )
    draft_p = Paragraph(draft_text, draft_banner_style)
    draft_table = Table([[draft_p]], colWidths=[A4[0] - 72])
    draft_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#FFF3CD')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#F0AD4E')),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(draft_table)
    story.append(Spacer(1, 10))

    # 2. Main Title & Subtitle
    story.append(Paragraph("SAFETY DATA SHEET", title_style))
    sub_text = (
        f"Product Name: <b>{sds.product_name}</b> &nbsp;|&nbsp; "
        f"Revision Date: {sds.revision_date} &nbsp;|&nbsp; "
        f"Prepared by: {sds.prepared_by}"
    )
    story.append(Paragraph(sub_text, subtitle_style))

    # 3. Red Alert Domain Warning Banner
    if warning_banner:
        warn_style = ParagraphStyle(
            'RedAlertText',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            leading=12.5,
            textColor=colors.HexColor('#991B1B')
        )
        warn_content = f"<b>CRITICAL DOMAIN & REGULATORY WARNING NOTICE:</b><br/>{warning_banner}"
        warn_p = Paragraph(warn_content, warn_style)
        warn_table = Table([[warn_p]], colWidths=[A4[0] - 72])
        warn_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#FEF2F2')),
            ('BOX', (0, 0), (-1, -1), 1.5, colors.HexColor('#DC2626')),
            ('LINELEFT', (0, 0), (-1, -1), 5, colors.HexColor('#991B1B')),
            ('PADDING', (0, 0), (-1, -1), 8),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(warn_table)
        story.append(Spacer(1, 10))

    # 4. GHS Signal Word & Pictograms Block
    signal = (sds.signal_word or "WARNING").upper()
    signal_color = colors.HexColor('#C53030') if signal == 'DANGER' else colors.HexColor('#DD6B20')
    signal_bg    = colors.HexColor('#FFF5F5') if signal == 'DANGER' else colors.HexColor('#FFFAF0')

    sig_p = Paragraph(f"<b>SIGNAL WORD: {signal}</b>", ParagraphStyle('SigWord', fontName='Helvetica-Bold', fontSize=12, textColor=signal_color))
    pics_p = Paragraph(f"GHS Pictograms: {', '.join(sds.pictogram_codes) if sds.pictogram_codes else 'GHS07'}", ParagraphStyle('Pics', fontName='Helvetica', fontSize=9, textColor=colors.HexColor('#4A5568')))

    ghs_box = Table([[sig_p, pics_p]], colWidths=[150, A4[0] - 72 - 150])
    ghs_box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), signal_bg),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#CBD5E0')),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(ghs_box)
    story.append(Spacer(1, 14))

    # 5. Render 16 GHS Sections
    for sec in sds.sections:
        sec_num = sec.section_number
        raw_title = sec.title or ""
        clean_title = re.sub(r'^(?:SECTION\s*\d+[\s:-]*)?(?:\d+[\s.:-]*)?', '', raw_title, flags=re.IGNORECASE).strip()
        header_text = f"SECTION {sec_num}: {clean_title.upper()}"

        hdr_p = Paragraph(header_text, section_header_style)
        hdr_table = Table([[hdr_p]], colWidths=[A4[0] - 72])
        hdr_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#1A365D')),
            ('PADDING', (0, 0), (-1, -1), 5),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))

        # Format body content with line breaks
        content_lines = sec.content.split('\n')
        formatted_lines = []
        for line in content_lines:
            line_str = line.strip()
            if not line_str:
                continue
            # Escaping HTML characters safely for reportlab Paragraph
            safe_line = line_str.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            # Bold key labels before colons (e.g., "CAS Number:", "Handling:")
            safe_line = re.sub(r'^([A-Za-z0-9\s/()_-]+:)', r'<b>\1</b>', safe_line)
            formatted_lines.append(safe_line)

        body_p = Paragraph("<br/>".join(formatted_lines), body_style)

        section_flowables = [
            hdr_table,
            Spacer(1, 4),
            body_p,
            Spacer(1, 10)
        ]
        story.append(KeepTogether(section_flowables))

    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_data = buffer.getvalue()
    buffer.close()
    return pdf_data
